name: CI

on:
  push:
  pull_request:

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install package manager
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          NEXT_PUBLIC_MAINNET_RPC_URL: ${{ secrets.NEXT_PUBLIC_MAINNET_RPC_URL }}
          NEXT_PUBLIC_DEVNET_RPC_URL: ${{ secrets.NEXT_PUBLIC_DEVNET_RPC_URL }}
        run: |
          echo "$NEXT_PUBLIC_MAINNET_RPC_URL"
          pnpm build

      - name: Code-style
        run: pnpm format:ci

      - name: Test
        env:
          NEXT_PUBLIC_MAINNET_RPC_URL: ${{ secrets.NEXT_PUBLIC_MAINNET_RPC_URL }}
          NEXT_PUBLIC_DEVNET_RPC_URL: ${{ secrets.NEXT_PUBLIC_DEVNET_RPC_URL }}
        run: |
          echo "$NEXT_PUBLIC_MAINNET_RPC_URL"
          echo "$NEXT_PUBLIC_DEVNET_RPC_URL"
          pnpm test:ci
